# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Term-HiliteDiff
version:      0.01
version_from: lib/Term/HiliteDiff.pm
installdirs:  site
requires:
    Algorithm::Diff:               0
    Exporter:                      0
    strict:                        0
    Test:                          0
    vars:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
